### ISSUE TITLE
Windows iguana-blaster

### ISSUE THREAD

**Issue by lamb0985** [pkscout/iguana-blaster#1]
i'm using the example codes to control my set top box, which work with the test command. if i try to run the execute.py -c 69 (just as an example), I get the following: 

C:\Users\Ryan>python "c:\program files (x86)\iguana-blaster\execute.py" -c 69                                           Traceback (most recent call last):                                                                                        File "c:\program files (x86)\iguana-blaster\execute.py", line 18, in <module>                                             from resources.lib.blast import Main                                                                                  File "c:\program files (x86)\iguana-blaster\resources\lib\blast.py", line 8, in <module>                                  from resources.lib.dvrs import *                                                                                      File "c:\program files (x86)\iguana-blaster\resources\lib\dvrs\nextpvr.py", line 3, in <module>                           from resources.lib.apis import nextpvr                                                                                File "c:\program files (x86)\iguana-blaster\resources\lib\apis\nextpvr.py", line 3, in <module>                           from . import url                                                                                                     File "c:\program files (x86)\iguana-blaster\resources\lib\apis\url.py", line 4, in <module>                               import requests as _requests                                                                                        ModuleNotFoundError: No module named 'requests' 

any ideas on how to fix this?

**Comment by pkscout** [comment]
I don't know why, but sometimes Python builds for Windows don't include the requests module.  Open up a command window and try this:
```
pip3 install requests
```
I haven't looked at this code in a **long** time, but that should fix it.  If that command doesn't work, you need to figure out how to install pip in your Windows Python install and then try the command again.

**Comment by lamb0985** [comment]
that worked for me to get version 3 up and running. I am having trouble because the IR receiver on my socket only iguana blaster isn't picking up on my remote key presses, so recording keys isn't working. I placed the example keys into the data folder, and thought this was working, but I think it's just picking up on my WinLIRC installation that has a working remote key config. I am able to change channels manually through command prompt with "c:\program files (x86)\iguana-blaster\"execute.py -c #whateverchannel.  

I have my npvr extras file setup to execute CMD then <args>/c "c:\program files (x86)\iguana-blaster\"execute.py -c {channel} | ffmpeg #allmyparametersforffmpeg</args>

This method previously worked when I had the hauppauge hd pvr 2 using:

haupblast {channel} | ffmpeg #allmyparametersforffmpeg

both should be getting the {channel} from the rest of the extras config. I know this may not be the place to post this, but support for this whole thing is extremely outdated and limited. I'll post my extras config file for my HDMI capture card at the end of this post. I also wonder why the iguanablast is only working if my WinLIRC is configured..seems weird that it's not working without it.

<extras>
	<channel name="{channel-name}">
      <command>cmd</command>
      <args>/c "c:\program files (x86)\iguana-blaster\"execute.py -c {channel} | ffmpeg -f dshow -rtbufsize 100M -video_size 1280x720 -framerate 60 -i video="USB3.0HD vid eo":audio="Digital Audio Interface (USB Digital Audio)" -c:v h264_qsv -b:v 15M -c:a aac -b:a 192k -f mpegts -</args>
    </channel>	
</extras>

**Comment by pkscout** [comment]
If you can change channels with the command prompt, then iguana blaster is probably working.  I can't help you with the hardware or WinLIRC, but my bet is that as long as WinLIRC is running the Iguana command line tool can't get control of the reciever to record commands.  You probably have to completely disable WinLIRC, learn the remote commands with the Iguana command line tool, and then re-enable WinLIRC.  I think you will have to have both, because you still need WinLIRC to get the remote commands and send them to NextPVR.  When I was using this, I had a Harmony remote with a FLIRC hardware dongle, so there was never any interaction I had to worry about between that and the Iguana hardware.  The FLIRC sent commands to NextPVR, then NextPVR sent the needed channel change commands to the external box via Iguana Blaster.  I'm honestly not sure if any of this will work if you're using WinLIRC with the Iguana hardware, as WinLIRC might take full control of the hardware and not let the command line work at all.

**Comment by lamb0985** [comment]
I was able to get out working after deleting winlirc and rebooting. I was lucky that the example keys control my spectrum set top box since I’ve still been unable to record input from the ir receiver port on the iguana blaster. Here is my working extras-capture.xml

<extras>
<channel name="{channel-name}">
<command>cmd</command>
<args>/c python.exe "c:\program files (x86)\iguana-blaster\execute.py" -c {channel} | ffmpeg -f dshow -rtbufsize 100M -video_size 1280x720 -framerate 60 -i video="USB3.0HD vid eo":audio="Digital Audio Interface (USB Digital Audio)" -c:v h264_qsv -b:v 15M -c:a aac -b:a 192k -f mpegts -</args>
</channel> 
</extras>

Thank you for your help with troubleshooting!

If it helps anyone I’ll link to my npvr blaster posts to show the process of how i got here. 
https://forums.nextpvr.com/showthread.php?tid=64495&page=2
